### ISSUE TITLE
Repos for user on show page should be listed by actual collaborator status, not substring matching

### ISSUE THREAD

**Issue by pconrad** [project-anacapa/anacapa-github-linker#107]
On the show page for a roster student, we can see the repos for that student.  

This requires running the "refresh_github_repos" job to update the table of github repos.

At the moment, the repos listed are selected on the basis of whether or not the userid is a substring of the repo name.

This job will change that so that the repos are listed if and only if the users is actually a "direct" collaborator (see: https://developer.github.com/v3/repos/collaborators/ ) on the repo.

**Comment by ProbablyFaiz** [comment]
Finished, with a surprising amount of difficulty in #116
