### ISSUE TITLE
Add to users index page, links to admin index and instructor index

### ISSUE THREAD

**Issue by pconrad** [project-anacapa/anacapa-github-linker#120]
Or, that might just be a "filter" that you can click.. maybe there's a button that adds a url param to the route such as ?type=admin  or ?type=instructor   

OR... maybe go ahead and bite the bullet and make nice tables that can be filtered and sorted and stuff, and paginated...

**Comment by ProbablyFaiz** [comment]
Done in #130 but possibly made redundant by the changes in #139.
