### ISSUE TITLE
Add github api rate limit to admin dashboard stats

### ISSUE THREAD

**Issue by pconrad** [project-anacapa/anacapa-github-linker#122]
Add a section for GitHub API to the admin dashboard.

* Display the username of the GITHUB_MACHINE_USER
* Get the current rate limit https://developer.github.com/v3/rate_limit/ and display the remaining and the reset

```
X-RateLimit-Remaining: 4999
X-RateLimit-Reset: 1372700873
```

For the reset value, it might be helpful to display that in some human friendly syntax.

**Comment by ProbablyFaiz** [comment]
Done in #125
