### ISSUE TITLE
Add link to github invitations 

### ISSUE THREAD

**Issue by pconrad** [project-anacapa/anacapa-github-linker#134]
On the page 

https://ucsb-cs-github-linker.herokuapp.com/courses/:course_id 

right after the place where it says: 

```
This course belongs to the github organization: ucsb-cs56-w20
```

Add a link that says:  

See Membership and Pending Invitations

and have the text  "Membership and Pending Invitations" link to, for example:

https://github.com/orgs/ucsb-cs56-w20/people

**Comment by ProbablyFaiz** [comment]
Done in #138
