### ISSUE TITLE
Slack integration for mapping slack name to github id and vice versa

### ISSUE THREAD

**Issue by pconrad** [project-anacapa/anacapa-github-linker#180]
As a user of the slack associated with a course
(which pre-supposes a way of associating a slack with a course), I can use a slack bot that allows me to map slack ids to github ids, and vice versa.

For example
```
/whois github pconrad
  Phill Conrad
  Instructor
  GitHub id: pconrad
  Slack id: pconrad  
```

Would return information about the user with github id pconrad, including the real name, role, github id and slack id of the user

```
/whois slack faiz
  Faiz Surani
  TA
  GitHub id: probablyfaiz
  Slack id: faiz
```

Later we might add things like GitHub team membership, section id, etc. but this is enough for now.

**Comment by ProbablyFaiz** [comment]
This will take some time. Will have to figure out how people's Slack accounts are associated with the student in the app, create the bot, write all the integration code etc. When do you want this?

**Comment by ProbablyFaiz** [comment]
Slack will be associated with users via a job that fetches list of users in a Slack workspace and compares their emails to the students' emails in the course.

### Useful Resources
- [slack-ruby-bot-server](https://github.com/slack-ruby/slack-ruby-bot-server)
