### ISSUE TITLE
BUG: Removing student from a team on Github doesn't get reflected in app

### ISSUE THREAD

**Issue by pconrad** [project-anacapa/anacapa-github-linker#222]
STR:  Add a student to two teams in Github. Run refresh github teams job.  Student shows up on two teams.  Remove student from one of those teams in Github.  Run refresh github teams job.
Observed: Student still shows up on both teams in Github Linker and Slack Bot
Desired: Student only shows up in one of the two teams.

**Comment by ProbablyFaiz** [comment]
#211 will resolve this via a webhook that is received when a user is removed from a team. For now, the only way to resolve this is to run the “Purge Github Info” (approximate name) and then the refresh team jobs again to flush out the old data, as the teams job doesn’t delete any existing records right now.
