### ISSUE TITLE
Enable webhooks doesn't work when creating *new* course

### ISSUE THREAD

**Issue by ProbablyFaiz** [project-anacapa/anacapa-github-linker#232]
If you click the "enable webhooks" button when the course is first being created, it throws an error.
Because it uses the course id, things go wrong when the course doesn't yet exist.

* STR: Try to create a new course and click "Enable WebHooks".
* Observed: The page crashes and the new course is not created.
* Desired Behavior: Course is created with webhooks enabled.

Workaround: 
* Create the course first
* Then edit it to enable webhooks

**Comment by pconrad** [comment]
Fixed in PR #292
