### ISSUE TITLE
Create repos for assignment from roster students

### ISSUE THREAD

**Issue by pconrad** [project-anacapa/anacapa-github-linker#305]
# Story

* As an instructor
* I can 
  - Enter an assignment name (e.g. `pa1`,  `lab00`, `proj3`)
  - For every github id of a roster student, `gh1`, gh2`, etc., repos will be created `pa1-gh1`, `pa1-gh2`, etc
  - I can specify visibility (public or private), and the level of access the student has (read, write, admin)
* So that
  - repo creation is easier
  - repos for assignments have a standard and predictable name

# Acceptance Criteria

- [ ] There is a web page (similar to the one at `courses/:course_num/org_teams/create_repos`) with a form where I can
        - enter assignment name
        - select read, write, admin 
        - select public or private 
        - click  a "Create Repos" button
- [ ] Legal assignment names contain letters, numbers, underscore and hyphen only
- [ ] When I click "Create Repos", repos are created for each roster student
- [ ] The repos have the correct permissions

**Comment by chundhau** [comment]
- Suggest labeling the feature "Create assignment" or "Create individual Assignment"
- Suggest labeling action button "Create assignment" or "Create Assignment and Generate Repos" instead of "Create Repos"
- Question: Will this work for team assignments or is this just for individual assignments?
