### ISSUE TITLE
Instructor functionality is broken

### ISSUE THREAD

**Issue by wpeery** [project-anacapa/anacapa-github-linker#39]
* As an instructor I should be able to create a course and add roster students
* Other Instructors should not be able to view/edit/delete my courses roster students
* As an Instructor I should be able to delete courses that I created

Right now what happens:
When I create a course as instructor, it says "You are not authorized to access this page" and it appears that the course is not created

**Comment by ProbablyFaiz** [comment]
This was fixed a long time ago, closing.
