### ISSUE TITLE
When a user changes their githubid, but keeps the same uid, the github linker breaks

### ISSUE THREAD

**Issue by pconrad** [project-anacapa/anacapa-github-linker#79]
This is because the username is used for the API calls instead of the uid.

Perhaps instead, consider using the UID.

The wrong username is also shown in the user info at upper right on the nav bar.  Again, on oauth authentication, consider updating the username from the github data.

**Comment by ProbablyFaiz** [comment]
Closing, this seems to have been fixed some time ago in 598a2d.
